const territoryData = [{ name: 'Taiwan', population: '23,773,876', territoryOf: 'China' },
  { name: 'Hong Kong', population: '7,436,154', territoryOf: 'China' },
  { name: 'Puerto Rico', population: '2,933,408', territoryOf: 'U.S.A.' },
  { name: 'Réunion', population: '888,927', territoryOf: 'France' },
  { name: 'Macao', population: '640,445', territoryOf: 'China' },
  { name: 'Guadeloupe', population: '400,056', territoryOf: 'France' },
  { name: 'Martinique', population: '375,554', territoryOf: 'France' },
  { name: 'French Guiana', population: '290,832', territoryOf: 'France' },
  { name: 'New Caledonia', population: '282,750', territoryOf: 'France' },
{ name: 'French Polynesia',
  population: '279,287', territoryOf: 'France' },
  { name: 'Mayotte', population: '266,150', territoryOf: 'France' },
  { name: 'Channel Islands', population: '172,259', territoryOf: 'U.K.' },
  { name: 'Guam', population: '167,294', territoryOf: 'U.S.A.' },
  { name: 'Curaçao', population: '163,424', territoryOf: 'Netherlands' },
  { name: 'Aruba', population: '106,314', territoryOf: 'Netherlands' },
  { name: 'U.S. Virgin Islands', population: '104,578', territoryOf: 'U.S.A.' },
  { name: 'Isle of Man', population: '84,584', territoryOf: 'U.K.' },
  { name: 'Cayman Islands', population: '64,948', territoryOf: 'U.K.' },
  { name: 'Bermuda', population: '62,506', territoryOf: 'U.K.' },
  { name: 'Northern Mariana Islands', population: '57,216', territoryOf: 'U.S.A.' },
  { name: 'Greenland', population: '56,672', territoryOf: 'Denmark' },
  { name: 'American Samoa', population: '55,312', territoryOf: 'U.S.A.' },
  { name: 'Faeroe Islands', population: '48,678', territoryOf: 'Denmark' },
  { name: 'Sint Maarten', population: '42,388', territoryOf: 'Netherlands' },
  { name: 'Turks and Caicos', population: '38,191', territoryOf: 'U.K.' },
  { name: 'Gibraltar', population: '33,701', territoryOf: 'U.K.' },
  { name: 'British Virgin Islands', population: '30,030', territoryOf: 'U.K.' },
  { name: 'Caribbean Netherlands', population: '25,979', territoryOf: 'Netherlands' },
{ name: 'Cook Islands', population: '17,548', territoryOf: 'New Zealand' },
  { name: 'Anguilla', population: '14,869', territoryOf: 'U.K.' },
  { name: 'Wallis & Futuna', population: '11,432', territoryOf: 'France' },
  { name: 'Saint Barthelemy', population: '9,847', territoryOf: 'U.K.' },
  { name: 'Saint Helena', population: '6,059', territoryOf: 'U.K.' },
  { name: 'Saint Pierre & Miquelon', population: '5,822', territoryOf: 'France' },
  { name: 'Montserrat', population: '4,989', territoryOf: 'U.K.' },
  { name: 'Falkland Islands', population: '3,377', territoryOf: 'U.K.' },
  { name: 'Niue', population: '1,615', territoryOf: 'New Zealand' },
  { name: 'Tokelau', population: '1,340', territoryOf: 'New Zealand' }
]

module.exports = territoryData;