const territoryData = [{ name: 'Taiwan', territoryPopulation: '23,773,876', territoryOf: 'China' },
  { name: 'Hong Kong', territoryPopulation: '7,436,154', territoryOf: 'China' },
  { name: 'Puerto Rico', territoryPopulation: '2,933,408', territoryOf: 'United States' },
  { name: 'Réunion', territoryPopulation: '888,927', territoryOf: 'France' },
  { name: 'Macao', territoryPopulation: '640,445', territoryOf: 'China' },
  { name: 'Guadeloupe', territoryPopulation: '400,056', territoryOf: 'France' },
  { name: 'Martinique', territoryPopulation: '375,554', territoryOf: 'France' },
  { name: 'French Guiana', territoryPopulation: '290,832', territoryOf: 'France' },
  { name: 'New Caledonia', territoryPopulation: '282,750', territoryOf: 'France' },
{ name: 'French Polynesia',
  territoryPopulation: '279,287', territoryOf: 'France' },
  { name: 'Mayotte', territoryPopulation: '266,150', territoryOf: 'France' },
  { name: 'Channel Islands', territoryPopulation: '172,259', territoryOf: 'United Kingdom' },
  { name: 'Guam', territoryPopulation: '167,294', territoryOf: 'United States' },
  { name: 'Curaçao', territoryPopulation: '163,424', territoryOf: 'Netherlands' },
  { name: 'Aruba', territoryPopulation: '106,314', territoryOf: 'Netherlands' },
  { name: 'U.S. Virgin Islands', territoryPopulation: '104,578', territoryOf: 'United States' },
  { name: 'Isle of Man', territoryPopulation: '84,584', territoryOf: 'United Kingdom' },
  { name: 'Cayman Islands', territoryPopulation: '64,948', territoryOf: 'United Kingdom' },
  { name: 'Bermuda', territoryPopulation: '62,506', territoryOf: 'United Kingdom' },
  { name: 'Northern Mariana Islands', territoryPopulation: '57,216', territoryOf: 'United States' },
  { name: 'Greenland', territoryPopulation: '56,672', territoryOf: 'Denmark' },
  { name: 'American Samoa', territoryPopulation: '55,312', territoryOf: 'United States' },
  { name: 'Faeroe Islands', territoryPopulation: '48,678', territoryOf: 'Denmark' },
  { name: 'Sint Maarten', territoryPopulation: '42,388', territoryOf: 'Netherlands' },
  { name: 'Turks and Caicos', territoryPopulation: '38,191', territoryOf: 'United Kingdom' },
  { name: 'Gibraltar', territoryPopulation: '33,701', territoryOf: 'United Kingdom' },
  { name: 'British Virgin Islands', territoryPopulation: '30,030', territoryOf: 'United Kingdom' },
  { name: 'Caribbean Netherlands', territoryPopulation: '25,979', territoryOf: 'Netherlands' },
{ name: 'Cook Islands', territoryPopulation: '17,548', territoryOf: 'New Zealand' },
  { name: 'Anguilla', territoryPopulation: '14,869', territoryOf: 'United Kingdom' },
  { name: 'Wallis & Futuna', territoryPopulation: '11,432', territoryOf: 'France' },
  { name: 'Saint Barthelemy', territoryPopulation: '9,847', territoryOf: 'United Kingdom' },
  { name: 'Saint Helena', territoryPopulation: '6,059', territoryOf: 'United Kingdom' },
  { name: 'Saint Pierre & Miquelon', territoryPopulation: '5,822', territoryOf: 'France' },
  { name: 'Montserrat', territoryPopulation: '4,989', territoryOf: 'United Kingdom' },
  { name: 'Falkland Islands', territoryPopulation: '3,377', territoryOf: 'United Kingdom' },
  { name: 'Niue', territoryPopulation: '1,615', territoryOf: 'New Zealand' },
  { name: 'Tokelau', territoryPopulation: '1,340', territoryOf: 'New Zealand' }
]

module.exports = { territoryData };